aborted_transactions_test.go, checksum_row_iterator.go, checksum_row_iterator_test.go, driver.go, driver_test.go, driver_with_mockserver_test.go, examples/hello/main.go, examples/transactions/main.go, integration_test.go, internal/statement_parser.go, internal/statement_parser_test.go, rows.go, rows_test.go, stmt.go, transaction.go
Updates all license headers to:
1. Use the same license header as in the client library.
2. Use 2021 as the copyright year.
=> chore: update license headers

rows.go, rows_test.go
The Next method should **always** set a value for each dest[i] element, even when it is nil, as the sql package reuses the same array for multiple calls to Next. This means that the previous value would be returned if the in some cases when the database value was NULL.
=> fix: always set a value for dest in Next

.github/workflows/integration-tests-on-production.yml
Skip integration tests on production for PRs that do not have access to the
GitHub secrets. This basically means all PRs that are created from forks.
The integration tests are still executed on the emulator, and they are executed
on production when the PR is merged with main.
=> build: skip integration tests on PROD for PRs from forks

driver.go, driver_with_mockserver_test.go
DDL statements cannot be executed as part of a transaction on Cloud Spanner.
Although it would be technically possible to execute a DDL statement while a
transaction is active, it could cause confusion whether the statement is part
of the transaction or not. The driver therefore should return an error if an
application tries to execute a DDL statement during an active transaction.
Fixes #31
=> fix: refuse DDL during transactions

driver.go, driver_with_mockserver_test.go, examples/go.mod, examples/go.sum, examples/mutations/main.go, transaction.go
Adds support for custom connection methods for using `Mutation`s with the Spanner go-sql driver.
=> feat: support mutations

examples/partitioned-dml/main.go
Adds a sample for using PDML with the go-sql driver.
=> docs: add sample for PDML

.github/workflows/integration-tests-on-production.yml, driver.go, driver_test.go, driver_with_mockserver_test.go, statement_parser.go
Fixes a potential race condition when the first action that a client application takes
is to open multiple connections in parallel. Each of these connections will try to compile
the client side statements the first time a statement is executed, but only one of them
should be allowed to do so. The rest should wait for the compilation to finish.
Also adds session configuration options to the connection string and caching of Spanner
clients that use the exact same connection string.
Fixes #58
=> fix: race condition when opening multiple connections in parallel as first action

integration_test.go
Fixes a minor TODO in the integration test.
=> test: use sql.NullString instead of spanner.NullString

README.md
Removes the non-supported disclaimer from the README, as it is no longer true.
=> docs: remove disclaimer from README

driver.go, driver_test.go
This adds a test case for handling invalid DSNs which currently can cause a panic in `extractConnectorConfig`.
Fixes #127
=> test: Add test for invalid DSN (which currently causes a panic)

driver.go
This extends `CheckNamedValue` to respect the `driver.Valuer` interface.
note: I realize this repository does not accept direct contributions and I am opening this as a nudge/suggestion.
Fixes #135
=> driver: Enable/respect driver.Valuer interface

.github/release-trigger.yml
Changes made in accordance with this [doc](https://docs.google.com/document/d/1TBFAk5fvfiGkjn1jxAiWq_0Bk66SVQSy7jpR-tMY9GY/edit?resourcekey=0-oMKo4qoXb5rR-lVWWex7oQ#).
A common [build file](https://critique.corp.google.com/cl/533065353), shared by all the Go split repos, is created for the release job.
=> chore(main): Enable release-trigger bot for triggering release job

driver.go
Fixes: https://github.com/googleapis/go-sql-spanner/issues/154
=> fix: initalize the connectors map to avoid nil pointer exception

driver.go, stmt.go
https://gorm.io/docs/models.html#gorm-Model declares field ID type uint for gorm, this PR will enable use of uint datatype with spanner driver
=> feat: support of uint for gorm.Model 

README.md, docs/limitations.rst
Clarify that this driver is for GoogleSQL support and that for the Spanner PostgreSQL Interface, the Go `database/sql` package can be used directly once PGAdapter is setup.
=> docs: clarify postgresql support

driver_with_mockserver_test.go, stmt.go
The driver did accept query parameters of type `uint`, but the underlying Spanner client would not accept these. `uint` query parameters therefore first need to be converted to `int64` and then sent to the Spanner client.
=> fix: support uint query params

client_side_statement.go, client_side_statement_test.go, client_side_statements_json.go, driver.go, driver_test.go, driver_with_mockserver_test.go
Adds a connection variable named `exclude_txn_from_change_streams` that can be used to exclude the next transaction from creating mutations for all change streams that have been created with the DDL option `allow_txn_exclusion=true`.
=> feat: add exclude_txn_from_change_streams variable

README.md, driver_with_mockserver_test.go, stmt.go
Named parameters that occurred multiple times in the SQL string had to be added to the list of arguments multiple times, even if these were given as named arguments. This fix allows queries that use named parameters to accept only one occurence of the named parameter.
This also clarifies the use of named parameters and positional parameters, and that mixing named parameters with positional arguments is not a good idea.
Based on the issue reported in #237
=> fix: support reusing named parameters

driver.go, integration_test.go, stmt.go, stmt_test.go
The types were mistyped as *[]uint and *[]int. Also adds an exhaustive test to all types listed in checkIsValidType.
It would be possible to support `*[]uint` as well, however, I'm not sure how useful it is.
=> fix: []*int and []*uint

driver.go, examples/struct-types/main.go
cloud.google.com/go/spanner supports passing structs as arguments to
queries.
Fixes #281
=> feat: support structs in queries

driver.go, driver_test.go
When a type had implemented custom Value func to convert the type,
then the conversion method was not being called for structs.
Fixes #281
=> fix: driver.Valuer method was being ignored

driver.go, driver_with_mockserver_test.go
This fixes a data race with regards to closing clients. I wasn't quite sure how to add a test for it.
=> fix: data-race with concurrent scan and close

examples/emulator_runner.go
When running the examples they leave unnecessary containers hanging
around. Add AutoRemove: true, to automatically remove them.
=> fix: autoremove container in examples

driver.go, examples/underlying-client/main.go
Sometimes the exposed features of go-sql-spanner are not sufficient to get the necessary response. This adds an escape hatch to access the underlying client.
Fixes #312
=> feat: expose underlying *spanner.Client

rows.go, rows_test.go
=> fix: return error when value conversion is missing

driver.go, driver_test.go, integration_test.go
Given a table like:
```
CREATE TABLE TestTable (Key INT64, IP BYTES(MAX), Duration INT64) PRIMARY KEY (Key)
```
I propose supporting writing and scanning from/to type aliases.
```
_, err = tx.ExecContext(ctx,
"INSERT INTO TestTable (key, ip, duration) VALUES (@key, @ip, @duration)",
123, net.IPv6loopback, time.Duration(1))
```
When using a struct as a model in an ORM (gorm for example), supporting type aliases makes those abstractions much more ergonomic.
=> types: support type aliases

driver.go, driver_test.go
Adds a GetBatchedStatements function that returns the currently buffered statements that will be executed if RunBatch is called. This gives applications the possibility of inspecting the list of buffered statements before actually executing them.
=> feat: add method for getting batched statements

driver.go, transaction.go
Transactions that are aborted by Spanner and that need to be retried should use the resetForRetry method, instead of creating a new transaction. This gives the retried transaction a higher priority, which again reduces the probability that the transaction will again be aborted by Spanner if it conflicts with another transaction with lower priority.
=> perf: use resetForRetry for retrying aborted transactions

.github/workflows/unit-tests.yml
The staticcheck GitHub Action is not allowed in this repository.
Fixes https://github.com/googleapis/go-sql-spanner/actions/runs/11879520599
=> build: remove staticcheck action

driver.go, driver_test.go
Adds a connection string option for disabling native metrics. Adding 'disableNativeMetrics=true'to the connection string will create a client config with native metrics disabled.
Fixes #310
=> feat: add option for disabling native metrics

examples/ddl-batches/main.go, examples/dml-batches/main.go, examples/mutations/main.go, examples/partitioned-dml/main.go, examples/stale-reads/main.go
Some of the examples missed a call to conn.Close().
Updates https://github.com/googleapis/google-cloud-go/issues/11017
=> docs: add missing conn.Close() calls

driver.go, driver_with_mockserver_test.go
Internal retries of aborted transactions is enabled by default for database/sql connections for Spanner. However, when an application or framework knows that it will retry the transaction using a retry-loop, it is more efficient to disable internal retries.
Some frameworks, such as gorm, however make this hard to achieve, as they only allow TxOptions to be used to configure the transaction, and do not give access to the underlying driver or connection.
This change adds a custom isolation level that can be used to disable internal retries of aborted transactions.
=> feat: add isolation level option for disabling internal retries

driver.go, driver_with_mockserver_test.go, integration_test.go, statement_parser.go, statement_parser_test.go, stmt.go
DML statements that were executed outside an explicit transaction would use a read-only transaction if the application called ExecQueryContext.
Fixes #235
=> fix: DML with THEN RETURN used read-only transaction

driver_with_mockserver_test.go, rows.go, testutil/mocked_inmem_server.go
PROTO columns are returned as []byte. ENUM columnns are returned as INT64. This enables the use of these columns through the standard database/sql Scan method.
Fixes #333
=> feat: return PROTO columns as bytes and integers

driver.go, stmt.go, stmt_with_mockserver_test.go
Refactor the connection code slightly to re-use more code for execution of prepared statements.
=> chore: simplify execution code for prepared statements

driver.go, driver_with_mockserver_test.go
Adds a function for starting a read/write transaction with additional Spanner options. The standard sql.DB.BeginTx function only accepts a small set of standardized options. This function allows any option that is supported by the Spanner Go client to be used for a database/sql transaction.
=> feat: begin read/write transaction with options

driver.go, driver_with_mockserver_test.go, examples/read-only-transaction-with-options/main.go
Adds a function for starting a read-only transaction with Spanner options. This function takes a custom Spanner ReadOnlyTransactionOptions struct as input argument, which in the future can be extended to add any new options that Spanner might add.
The transaction options that are given for the transaction are only used for this one transaction, instead of being persisted on the connection.
=> feat: read-only transaction with options

checksum_row_iterator.go, client_side_statement.go, driver.go, examples/auto-partition-queries/main.go, merged_row_iterator.go, partitioned_query.go, partitioned_query_test.go, rows.go, rows_test.go, testutil/inmem_spanner_server.go, transaction.go
Adds support for automatically partitioning queries, executing each partition, and merge the results that are returned into a single row iterator. This allows applications, tools, and frameworks to use partitioned queries as if they were normal queries.
=> feat: auto-partition queries

driver.go, driver_test.go, driver_with_mockserver_test.go, examples/data-types/main.go, rows.go, testutil/mocked_inmem_server.go
Adds an option to decode arrays to primitive Go array types. This enables the use of []bool, []int64, []float32, []float64, and []string arrays with the Spanner database/sql driver.
Enabling this option and trying to decode an array that contains a NULL element will result in an error being returned.
Fixes #331
Updates https://github.com/googleapis/go-gorm-spanner/issues/130
Updates https://github.com/googleapis/go-gorm-spanner/issues/133
=> feat: option for decode to native array

aborted_transactions_test.go, driver.go, return_last_insert_id_test.go, stmt.go, transaction.go
Adds support for LastInsertId in read/write transactions.
Fixes #346
=> feat: support LastInsertId in transactions

aborted_transactions_test.go, transaction.go
The driver would leak a session if a read/write transaction was aborted during a Commit, and the retry of the transaction would fail due to concurrently modified data.
Fixes #380
=> fix: session leak when tx was aborted during commit

.github/workflows/integration-tests-on-emulator.yml, .github/workflows/samples.yml, .github/workflows/snippets.yml, .github/workflows/unit-tests.yml, README.md
Updates the policy for the supported Go versions and updates the test runners to use the two latest versions.
=> deps: update supported Go version to 1.24

conn.go, conn_with_mockserver_test.go, driver.go, driver_test.go
Add support for isolation level REPEATABLE READ with the BeginTx function. This allows the caller to specify the isolation level for a single transaction. A follow-up pull request will add support for setting the default isolation level that should be used by a connection.
=> feat: support isolation level REPEATABLE READ

conn.go, conn_with_mockserver_test.go, driver.go, driver_test.go
Support setting a default isolation level for a connection and connector. All read/write transactions on a connection will use the default isolation level, unless an isolation level is specified in the BeginTx function call.
=> feat: support default isolation level for connection

driver.go, driver_test.go
Do not include the Configurator func when marshalling a ConnectorConfig to json.
Fixes #409
=> fix: skip Configurator func when marshalling to json

.github/workflows/integration-tests-on-emulator.yml, .github/workflows/samples.yml, .github/workflows/snippets.yml, .github/workflows/unit-tests.yml
Run tests for pull requests on any branch.
=> build: run tests pull requests for all branches

conn.go, conn_with_mockserver_test.go
Fixes: https://github.com/googleapis/go-sql-spanner/issues/437
=> fix: return explicit error message when using DDL statements with QueryContext

conn.go, driver.go, driver_with_mockserver_test.go, integration_test.go, statement_parser.go, statement_parser_test.go, testutil/inmem_spanner_server.go, testutil/mocked_inmem_server.go
Automatically detect the dialect of the database that the driver connects to, and modify the way that query parameters are recognized based on the dialect of the database. This makes it possible to use this driver with Spanner databases that use the PostgreSQL dialect.
=> feat: detect database dialect and support PostgreSQL databases

conn.go, driver.go, driver_with_mockserver_test.go, integration_test.go, statement_parser.go, statement_parser_test.go, testutil/inmem_spanner_server.go, testutil/mocked_inmem_server.go
Adds support for dollar-quoted strings.
Also fixes an issue in the skipWhitespaces function, where multi-byte characters would be skipped as-if they were spaces.
=> chore: add support for dollar-quoted strings

benchmarks/go.mod, benchmarks/go.sum, conn.go, driver.go, driver_test.go, driver_with_mockserver_test.go, examples/go.mod, examples/go.sum, go.mod, go.sum, integration_test.go, snippets/go.mod, snippets/go.sum, statement_parser.go, statement_parser_test.go, stmt.go, testutil/inmem_spanner_server.go, testutil/mocked_inmem_server.go
The functions for determining the type of statement and which query parameters are in a statement are deterministic and do not change over time. These can therefore safely be cached. This improves the execution speed of frequently executed SQL strings, as the same parsing does not need to happen for each execution.
=> perf: add a cache for parsed statements

README.md, examples/emulator_runner.go, examples/postgresql/main.go
The driver now supports both GoogleSQL and PostgreSQL databases.
The driver automatically detects the dialect of the database that it is connected to, and adjusts the query parameter styles and comments that it accepts accordingly.
=> feat: support PostgreSQL-dialect databases

driver.go, driver_test.go, driver_with_mockserver_test.go, examples/statement-cache/main.go
A statement cache has been added to the driver to prevent SQL strings from being parsed repeatedly for each execution. Instead, a SQL string is parsed once and the results of this parsing is added to an internal cache. Only the parse result is added to the cache, and not the results of the actual execution of the statement.
=> perf: use statement cache to avoid repeated SQL string parsing

emulator_util.go, integration_test.go
Wrap the AlreadyExists error when instance creation fails with autoConfigEmulator=true.
This ensures that the error is correctly recognized, and that the error is not propagated
to the application.
Credits to @DanielvNiek for spotting and fixing this in the first place.
Replaces #449
Fixes #448
=> fix: wrap AlreadyExists error for instance creation when autoConfigEmulator=true

conn.go, driver.go, driver_with_mockserver_test.go
Adds an option to directly execute the query when QueryContext is called. Without this option, the query execution is delayed until the first call to Rows.Next. This again also delays any query errors until the first call to Rows.Next, which can be confusing in some cases.
=> feat: add DirectExecuteQuery option

conn.go, conn_with_mockserver_test.go, driver.go, driver_test.go, driver_with_mockserver_test.go
Adds a BeginTransactionOption configuration field that can be used to determine how the database/sql driver should begin transactions. The default is to inline the BeginTransaction option with the first SQL statement of the transaction. This reduces the number of round-trips needed per transaction by one for most transaction shapes.
=> feat: add BeginTransactionOption

driver.go, emulator_util.go
Fixes: https://github.com/googleapis/go-sql-spanner/issues/459
=> fix: use client opts to auto configure emulator instead of environment variable

aborted_transactions_test.go, auto_dml_batch_test.go, conn.go, conn_with_mockserver_test.go, driver.go, driver_test.go, driver_with_mockserver_test.go
Inline the BeginTransaction option with the first statement in the transaction, instead of executing a separate BeginTransaction RPC. This reduces the number of round-trips to Spanner by one for all transactions that have at least one SQL statement.
Using line-begin improves performance for most transaction shapes, as it requires one less round-trip to Spanner. Some transaction shapes do not benefit from this. These are:
1. Transactions that only write mutations still need an explicit BeginTransaction RPC to be executed, as mutations are included in the Commit RPC. The Commit RPC can also start a transaction, but such transactions are not guaranteed to be applied only once to Spanner.
2. Transactions that execute multiple parallel queries at the start of the transaction can see higher …
=> perf: inline BeginTransaction with first statement

client_side_statement.go, client_side_statement_test.go, conn.go, rows.go, statement_parser.go
Return ResultSetMetadata and ResultSetStats as separate result sets if the caller has requested this in the ExecOptions. This ensures that client-side statements behave the same as statements that are executed by Spanner.
=> feat: return metadata and stats for client-side statements

.github/workflows/release-dotnet-native-spanner-lib.yml, .github/workflows/release-dotnet-spanner-lib.yml
Creates release scripts for the .NET wrappers of the shared library. These are not executed automatically for pull requests or any other events. They can only be executed manually.
=> build: create dotnet release scripts

conn_with_mockserver_test.go, statement_parser.go, statement_parser_test.go, statements.go, testutil/inmem_database_admin_server.go
Support CREATE DATABASE and DROP DATABASE statements.
=> feat: create/drop database statements

conn.go, conn_with_mockserver_test.go, rows.go, rows_test.go
Allow DDL statements to be used with the QueryContext function. This makes the function a 'catch-all' function that can be used for all types of statements, without having to worry beforehand what the type of statement is. The driver returns an empty row iterator for DDL statements.
=> feat: allow DDL statements with QueryContext

aborted_transactions_test.go, auto_dml_batch_test.go, conn_with_mockserver_test.go, driver_with_mockserver_test.go, partitioned_query_test.go, stmt_with_mockserver_test.go, testutil/inmem_spanner_server.go
Move a couple of test utility functions to the testutil package, so these can be used from any subpackage as well.
=> test: move utility functions to testutil

conn.go, conn_with_mockserver_test.go, parser/simple_parser.go, parser/statement_parser.go, parser/statement_parser_test.go, parser/statements.go, parser/statements_test.go, statements.go, stmt.go
Add support for BEGIN, COMMIT and ROLLBACK SQL statements.
=> feat: support BEGIN, COMMIT and ROLLBACK statements

conn.go, spannerlib/api/batch_test.go, spannerlib/api/connection.go, spannerlib/api/connection_test.go, spannerlib/lib/connection.go, spannerlib/lib/connection_test.go, spannerlib/shared/shared_lib.go, spannerlib/shared/shared_lib_test.go, spannerlib/wrappers/spannerlib-java/src/main/java/com/google/cloud/spannerlib/Connection.java, spannerlib/wrappers/spannerlib-java/src/main/java/com/google/cloud/spannerlib/internal/SpannerLibrary.java, spannerlib/wrappers/spannerlib-java/src/test/java/com/google/cloud/spannerlib/BatchTest.java, spannerlib/wrappers/spannerlib-java/src/test/java/com/google/cloud/spannerlib/ConnectionTest.java
Adds an ExecuteBatch function to SpannerLib that supports executing DML or DDL statements as a single batch. The function accepts an ExecuteBatchDml request for both types of batches. The type of batch that is actually being executed is determined based on the statements in the batch. Mixing DML and DDL in the same batch is not supported. Queries are also not supported in batches.
=> chore: add ExecuteBatch to SpannerLib

conn.go, conn_with_mockserver_test.go, spannerlib/api/batch_test.go, spannerlib/api/connection.go, spannerlib/api/connection_test.go, spannerlib/api/transaction_test.go, spannerlib/lib/connection.go, spannerlib/lib/connection_test.go, spannerlib/shared/shared_lib.go, spannerlib/shared/shared_lib_test.go, spannerlib/wrappers/spannerlib-java/src/main/java/com/google/cloud/spannerlib/Connection.java, spannerlib/wrappers/spannerlib-java/src/main/java/com/google/cloud/spannerlib/internal/SpannerLibrary.java, spannerlib/wrappers/spannerlib-java/src/test/java/com/google/cloud/spannerlib/BatchTest.java, spannerlib/wrappers/spannerlib-java/src/test/java/com/google/cloud/spannerlib/ConnectionTest.java, spannerlib/wrappers/spannerlib-java/src/test/java/com/google/cloud/spannerlib/TransactionTest.java, statements.go, transaction.go
Adds BeginTransaction, Commit, and Rollback functions for the shared library.
=> chore: add transaction support for SpannerLib

conn.go, connection_properties.go, driver.go, driver_with_mockserver_test.go, spannerlib/api/transaction_test.go, transaction.go
Store temporary TransactionOptions in the connection state as local options. Local options only apply to the current transaction. This simplifies the internal state handling of the driver, as all transaction state should only be read from the connection state, and not also from a temporary variable.
This also enables the use of a combination of temporary transaction options and using SQL statements to set further options. The shared library always includes temporary transaction options, as the BeginTransaction function accepts TransactionOptions as an input argument. This meant that using SQL statements to set further transaction options was not supported through the shared library.
=> chore: store temp TransactionOptions in connection state
